# Generated by Django 4.2 on 2023-05-12 02:45

from django.db import migrations
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission



def create_delivery_crew(apps,schemma_migration):
    try:
        group = Group.objects.create(name='deliverycrew')
        view_order = Permission.objects.get(codename='view_order')
        change_order = Permission.objects.get(codename = 'change_order')
        permission = [view_order,
                      change_order]
        group.permissions.set(permission)
    except:
        pass



class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_delivery_crew),
          

    ]


