# Generated by Django 4.2 on 2023-05-18 01:17

from django.db import migrations
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
# does not grant permissions to manager group TODO
def create_manager(apps,schemma_migration):
        group = Group.objects.create(name='manager')
        add_menuitems = Permission.objects.get(codename='add_menu_items')
        change_menuitems = Permission.objects.get(codename = 'change_menu_items')
        delete_menuitems = Permission.objects.get(codename = 'delete_menu_items')
        view_menuitems = Permission.objects.get(codename = 'view_menu_items')
        change_group = Permission.objects.get(codename ='change_group')


        permission = [add_menuitems,
                      change_menuitems,
                      delete_menuitems,
                      view_menuitems,
                      change_group]
        
        group.permissions.set(permission)
   

class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_auto_20230511_1945'),
    ]

    operations = [
        migrations.RunPython(create_manager),
    ]
